### PR TITLE
Fix GCC 6 warnings

### PR DESCRIPTION
**Pull request by vvidic**
Please review patches fixing warnings reported during build using GCC 6.

### CODE REVIEW

**Comment by josephhz** [comment]
For patch "Fix uninitialized progname in mkfs.c", it will be initialized by the following code:
if (argc && *argv)
    progname = basename(argv[0]);

For patch "Replace register_printf_function with register_printf_specifier", it will cause old kernel build failure, please refer to commit 3e692a9a0ee2 ("vendor: rhel5: fix build failure") for details.

Others looks good to me.

Thanks,
Joseph

**Comment by vvidic** [comment]
GCC6 warns about ``progname`` for some reason because of the if statement. Maybe the ``argc/argv`` check chould be removed if it is always true?

**Comment by vvidic** [comment]
Regarding ``register_printf_specifier`` maybe it can be tested somehow and used if exists? If not I can carry this patch in the Debian package for now as it is simple enough.

**Comment by vvidic** [comment]
Updated the fixes with your comments and added two more fixes for GCC-7 warnings. Please check again.

**Comment by josephhz** [comment]
patch "Conditionaly replace register_printf_function" still has compiling error in RHEL6:

op_query.c: In function ‘query_run’:
op_query.c:328: warning: implicit declaration of function ‘register_printf_specifier’
op_query.o: In function `query_run':
op_query.c:(.text+0xb4): undefined reference to `register_printf_specifier'
op_query.c:(.text+0xca): undefined reference to `register_printf_specifier'
op_query.c:(.text+0xe0): undefined reference to `register_printf_specifier'
op_query.c:(.text+0xf6): undefined reference to `register_printf_specifier'
op_query.c:(.text+0x10c): undefined reference to `register_printf_specifier'
op_query.o:op_query.c:(.text+0x122): more undefined references to `register_printf_specifier' follow
collect2: ld returned 1 exit status
make[1]: *** [ocfs2ne] Error 1
make: *** [tunefs.ocfs2] Error 2

**Comment by vvidic** [comment]
Just tested on CentOS 6.8 and the build works there with the register_printf_specifier defined. Did you mean RHEL5 perhaps?

**Comment by josephhz** [comment]
From the above error message I think it won't work without register_printf_specifier defined. So I suggest we leave this warning and let others merge first.

**Comment by vvidic** [comment]
Agreed, removed register_printf_specifier patch so you can take the rest.

**Pull request merged**
